_wandb:
    value:
        cli_version: 0.25.1
        e:
            potmm8micrpu19vbqe0e7cj3vzk16niq:
                args:
                    - --pad_to_max_length
                    - --wd_LN_gamma
                    - --with_tracking
                    - --report_to
                    - wandb
                    - --run_name
                    - test_vanilla_llama3_1b
                    - --extra_tb_stats
                    - --seed
                    - "1000"
                    - --dataset_setup
                    - bookcorpus_and_wiki
                    - --preprocessing_num_workers
                    - "10"
                    - --data_cache_dir
                    - /scratch/hlv8980/residual/.hf_data
                    - --model_cache_dir
                    - /scratch/hlv8980/residual/.hf_cache
                    - --model_type
                    - llama
                    - --tokenizer_name
                    - meta-llama/Llama-3.2-1B
                    - --max_seq_length
                    - "2048"
                    - --block_size
                    - "512"
                    - --learning_rate
                    - "0.0004"
                    - --lr_scheduler_type
                    - linear
                    - --max_train_steps
                    - "100000"
                    - --num_warmup_steps
                    - "2000"
                    - --per_device_train_batch_size
                    - "48"
                    - --per_device_eval_batch_size
                    - "48"
                    - --gradient_accumulation_steps
                    - "4"
                    - --max_grad_norm
                    - "1.0"
                    - --weight_decay
                    - "0.1"
                    - --checkpointing_steps
                    - "5000"
                    - --tb_scalar_log_interval
                    - "10000"
                    - --tb_hist_log_interval
                    - "20000"
                    - --model_name_or_path
                    - meta-llama/Llama-3.2-1B
                    - --attn_softmax
                    - vanilla
                    - --attn_res_softmax_fn
                    - vanilla
                    - --output_dir
                    - /scratch/hlv8980/residual/output/vanilla_llama3
                codePath: run_clm_ddp.py
                codePathLocal: run_clm_ddp.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "540905459712"
                        used: "7807549440"
                email: logan.yang2002@gmail.com
                executable: /home/hlv8980/.conda/envs/outlier/bin/python
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-7d537fa9-022f-ad3a-2169-a94177378ccf
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-2cfc2299-2aa4-e742-5d47-f347ffde74dc
                host: qgpu3008
                memory:
                    total: "1081810919424"
                os: Linux-4.18.0-553.64.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /gpfs/projects/p32013/residual/OutEffHop/run_clm_ddp.py
                python: CPython 3.9.18
                root: /gpfs/projects/p32013/residual/OutEffHop
                slurm:
                    job_id: "3327418"
                startedAt: "2026-03-23T08:49:31.001656Z"
                writerId: potmm8micrpu19vbqe0e7cj3vzk16niq
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 105
            "3":
                - 13
            "4": 3.9.18
            "5": 0.25.1
            "6": 4.57.6
            "8":
                - 2
            "12": 0.25.1
            "13": linux-x86_64
alpha:
    value: null
attn_dropout:
    value: null
attn_gate_init:
    value: 0.5
attn_gate_linear_all_features:
    value: false
attn_gate_mlp:
    value: false
attn_gate_mlp2:
    value: false
attn_gate_type:
    value: none
attn_res_softmax_fn:
    value: vanilla
attn_softmax:
    value: vanilla
block_size:
    value: 512
checkpointing_steps:
    value: "5000"
config_name:
    value: null
config_path:
    value: null
data_cache_dir:
    value: /scratch/hlv8980/residual/.hf_data
dataset_setup:
    value: bookcorpus_and_wiki
est_num_batches:
    value: 1
extra_tb_stats:
    value: true
final_lr_fraction:
    value: 0
fine_tuning:
    value: false
grad_norm_type:
    value: 2
gradient_accumulation_steps:
    value: 4
hidden_dropout:
    value: null
learning_rate:
    value: 0.0004
low_cpu_mem_usage:
    value: false
lr_scheduler_type:
    value: linear
max_checkpointing_number:
    value: 2
max_grad_norm:
    value: 1
max_seq_length:
    value: 2048
max_train_steps:
    value: 100000
mlm_probability:
    value: 0.15
model_cache_dir:
    value: /scratch/hlv8980/residual/.hf_cache
model_name_or_path:
    value: meta-llama/Llama-3.2-1B
model_output_dir:
    value: null
model_type:
    value: llama
n_bits:
    value: 8
n_bits_act:
    value: 8
no_act_quant:
    value: false
no_weight_quant:
    value: false
num_train_epochs:
    value: 4
num_warmup_steps:
    value: 2000
output_dir:
    value: /scratch/hlv8980/residual/output/vanilla_llama3
overwrite_cache:
    value: false
pad_to_max_length:
    value: true
per_device_eval_batch_size:
    value: 48
per_device_train_batch_size:
    value: 48
percentile:
    value: null
preprocessing_num_workers:
    value: 10
qmethod_acts:
    value: asymmetric_uniform
quant_setup:
    value: all
quantize:
    value: false
ranges_acts:
    value: running_minmax
ranges_weights:
    value: minmax
report_to:
    value: wandb
resume_from_checkpoint:
    value: null
run_name:
    value: test_vanilla_llama3_1b
save_quantize_model:
    value: false
seed:
    value: 1000
skip_attn:
    value: false
tb_hist_log_interval:
    value: 20000
tb_scalar_log_interval:
    value: 10000
tokenizer_name:
    value: meta-llama/Llama-3.2-1B
tqdm_update_interval:
    value: 100
train_percentage:
    value: null
use_slow_tokenizer:
    value: false
validation_percentage:
    value: null
wd_LN_gamma:
    value: true
weight_decay:
    value: 0.1
with_tracking:
    value: true
